packages:
  - packages/*
  - test

catalogs:
  dev:
    '@commitlint/cli': ^20.4.1
    '@commitlint/config-conventional': ^20.4.1
    '@commitlint/types': ^20.4.0
    '@lerna-lite/cli': ^4.11.2
    '@lerna-lite/publish': ^4.11.2
    '@types/node': ^25.2.2
    eslint: ^9.39.2
    husky: ^9.1.7
    lint-staged: ^16.2.7
    prettier: ^3.8.1
    rimraf: ^6.1.2
    sort-package-json: ^3.6.1
    typescript: ^5.9.3
    tsdown: ^0.20.3

  dev-test:
    vue: ^3.5.28

  prod:
    '@meteorlxy/eslint-config': ^6.12.0
    '@typescript-eslint/utils': ^8.54.0
    eslint-plugin-vue: ^10.7.0
    vue-eslint-parser: ^10.2.0
