packages:
  - packages/*
  - test

catalogs:
  dev:
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    '@commitlint/types': ^19.8.1
    '@lerna-lite/cli': ^4.8.0
    '@lerna-lite/publish': ^4.8.0
    eslint: ^9.36.0
    husky: ^9.1.7
    lint-staged: ^16.2.0
    prettier: ^3.6.2
    rimraf: ^6.0.1
    sort-package-json: ^3.4.0
    typescript: ^5.9.2
    tsdown: ^0.15.4

  dev-test:
    vue: ^3.5.21

  prod:
    '@meteorlxy/eslint-config': ^6.6.2
    '@typescript-eslint/utils': ^8.44.1
    eslint-plugin-vue: ^10.5.0
    vue-eslint-parser: ^10.2.0
